# Generated by Django 5.2.12 on 2026-03-26 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_quiz_attemp_user_id_idx_quiz_attemp_user_id_ca54ed_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_length', models.PositiveIntegerField(help_text='Expected number of questions for this session.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Session',
                'verbose_name_plural': 'Quiz Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The session this attempt belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quizsession'),
        ),
    ]
