# Generated by Django 6.0.1 on 2026-04-04 21:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_length', models.PositiveIntegerField(help_text='Expected number of questions for this session.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Session',
                'verbose_name_plural': 'Quiz Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('mastery_score', models.IntegerField(default=50, help_text='AI calculated mastery score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('Weak', 'Weak (Needs Practice)'), ('Average', 'Average'), ('Strong', 'Strong (Spaced Repetition)')], default='Average', max_length=20)),
                ('last_evaluated', models.DateTimeField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, help_text="AI's reasoning for the current mastery level.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='quiz_core.chapter')),
                ('tags', models.ManyToManyField(blank=True, related_name='topics', to='quiz_core.tag')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The question text shown to the user.')),
                ('options', models.JSONField(help_text="List of answer options as a JSON array, e.g. ['A', 'B', 'C', 'D']")),
                ('correct_answer', models.CharField(help_text='The correct answer string. Must match one of the options.', max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10)),
                ('solution_image', models.URLField(blank=True, help_text='Optional URL to an image showing the detailed solution.', null=True)),
                ('expected_time_seconds', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='quiz_core.tag')),
                ('topic', models.ForeignKey(help_text='The topic this question belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_core.topic')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['topic', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(default=0.0, help_text='Overall accuracy as a percentage (0–100).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('avg_time', models.FloatField(default=0.0, help_text='Average time taken per question in seconds.')),
                ('weak_topics', models.JSONField(blank=True, default=list, help_text='Topics where accuracy < 50%. Computed by analysis engine.')),
                ('strong_topics', models.JSONField(blank=True, default=list, help_text='Topics where accuracy > 75%. Computed by analysis engine.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(help_text='The answer the user chose.', max_length=255)),
                ('is_correct', models.BooleanField(default=False, help_text='Set automatically by comparing selected_answer to correct_answer.')),
                ('time_taken', models.PositiveIntegerField(help_text='Time taken to answer, in seconds. Sent from the frontend timer.')),
                ('hints_used', models.PositiveIntegerField(default=0, help_text='Number of hints used during this attempt.')),
                ('bookmarked', models.BooleanField(default=False, help_text='True if the user marked this question for later review.')),
                ('notes_text', models.TextField(blank=True, help_text='Optional text note added by the user for this question.', null=True)),
                ('notes_audio', models.FileField(blank=True, help_text='Optional audio note file upload.', null=True, upload_to='audio_notes/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz_core.question')),
                ('session', models.ForeignKey(blank=True, help_text='The session this attempt belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz_core.quizsession')),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'question'], name='quiz_core_a_user_id_ff784d_idx')],
            },
        ),
    ]
