# Generated by Django 6.0.1 on 2026-04-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='recommended_subtopics',
            field=models.JSONField(blank=True, default=list, help_text='List of precise sub-topics generated dynamically by the AI for focused study.'),
        ),
    ]
