# Generated by Django 6.0.1 on 2026-04-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_core', '0002_topic_recommended_subtopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='mastery_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='recommended_subtopics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='status',
            field=models.CharField(default='Average', max_length=20),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='topic_name',
            field=models.CharField(blank=True, help_text='Custom name for this quiz session.', max_length=255, null=True),
        ),
    ]
