# Generated by Django 6.0.1 on 2026-04-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='last_evaluated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
