# Generated by Django 5.2.12 on 2026-03-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attempt',
            new_name='quiz_attemp_user_id_ca54ed_idx',
            old_name='quiz_attemp_user_id_idx',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='bookmarked',
            field=models.BooleanField(default=False, help_text='True if the user marked this question for later review.'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Set automatically by comparing selected_answer to correct_answer.'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='notes_text',
            field=models.TextField(blank=True, help_text='Optional text note added by the user for this question.', null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='time_taken',
            field=models.PositiveIntegerField(help_text='Time taken to answer, in seconds. Sent from the frontend timer.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='strong_topics',
            field=models.JSONField(blank=True, default=list, help_text='Topics where accuracy > 75%. Computed by analysis engine.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weak_topics',
            field=models.JSONField(blank=True, default=list, help_text='Topics where accuracy < 50%. Computed by analysis engine.'),
        ),
    ]
